CREATE SCHEMA IF NOT EXISTS bitetrack_dev;

GRANT ALL ON SCHEMA bitetrack_dev TO CURRENT_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA bitetrack_dev GRANT ALL ON TABLES TO CURRENT_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA bitetrack_dev GRANT ALL ON SEQUENCES TO CURRENT_USER;
